package nl.esciencecenter.ptk.vbrowser.viewers.events;

public enum ViewerEventType {
    VIEWER_STARTED, VIEWER_STOPPED, VIEWER_DISPOSED, HYPERLINK_EVENT, HYPERLINK_OPEN_NEW,
    HYPERLINK_LINK_FOLLOWED, HYPERLINK_FRAMELINK_FOLLOWED
}